version: '3.8'
services:
  bot:
    build: .
    image: topstep_quant:latest
    container_name: topstep_bot
    restart: unless-stopped
    environment:
      # Trading API credentials (example, replace with real values or use secrets)
      TOPSTEP_API_USER: "${TOPSTEP_API_USER:-}"      # e.g., your Topstep or broker username
      TOPSTEP_API_PASS: "${TOPSTEP_API_PASS:-}"      # e.g., your Topstep or broker password
      # Risk limit configurations (can override defaults if needed)
      DAILY_LOSS_LIMIT: "1000"
      TRAILING_MAX_DRAWDOWN: "2000"
      # Other configuration
      BOT_MODE: "live"                # or "dry-run" for simulation mode
      PROMETHEUS_METRICS_PORT: "8000" # port for metrics server (if configurable in code)
    ports:
      - "8000:8000"  # expose bot's Prometheus metrics endpoint to host (optional)
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
