# Prometheus configuration for TopstepQuant monitoring
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'topstep-quant-bot'
    static_configs:
      - targets: ['bot:8000']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']